[package]
name = "rox-bridge"
version = "0.1.0"
edition = "2021"
description = "ROS 2 / Zenoh bridge for Rox"

[dependencies]
rox-protocol = { path = "../rox-protocol" }
rox-transport = { path = "../rox-transport" }
tokio = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
