[package]
name = "rox-protocol"
version = "0.1.0"
edition = "2021"
description = "Wire protocol definitions for Rox"

[dependencies]
bytes = { workspace = true }
serde = { workspace = true }
nom = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
